import type { Review } from "./reviews-data";

export const fullReviews: Review[] = [
  {
  id: "add9",
  username: "ljubljana_hive",
  avatar: "https://i.pravatar.cc/60?img=48",
  flag: "https://flagcdn.com/24x18/si.png",
  country: "Slovenia",
  timeAgo: "9 months ago",
  rating: 5,
  text: "Organic honey store with subscriptions and educational content. The community features helped us keep buyers coming back monthly.",
  priceRange: "$380",
  duration: "8 days",
  serviceType: "Organic Honey Store + Subscriptions",
  gigImage: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609381/IMG-20250921-WA0028_bwhztb.jpg",
  reply: "Love what you're building around sustainability — happy to support it online.",
  showHelpful: false,
  },
  {
  id: "fr9",
  username: "helsinki_hub",
  avatar: "https://i.pravatar.cc/60?img=30",
  flag: "https://flagcdn.com/24x18/fi.png",
  timeAgo: "4 months ago",
  rating: 5,
  text: "Complex B2B Shopify build handled with care. ERP connections work, the admin side is clear, and Google Ads is bringing qualified leads — not noise.",
  priceRange: "$750",
  duration: "12 days",
  serviceType: "B2B E-commerce Solution",
  gigImage: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609381/IMG-20250921-WA0028_bwhztb.jpg",
  reply: "Thanks for the partnership — glad the B2B setup is running smoothly for your team.",
  showHelpful: false,
  },
  {
  id: "fr5",
  username: "osaka_outfit",
  avatar: "https://i.pravatar.cc/60?img=33",
  flag: "https://flagcdn.com/24x18/jp.png",
  timeAgo: "2 months ago",
  rating: 5,
  text: "Bofowo launched our fashion Shopify store with a look that matches the brand. Checkout is smooth and the email flows he set up are already bringing repeat buyers.",
  priceRange: "$380",
  duration: "5 days",
  serviceType: "Fashion Store Build",
  gigImage: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609405/IMG-20250921-WA0043_pdhfii.jpg",
  reply: "Appreciate it — your collection deserves a strong storefront. Rooting for you!",
  showHelpful: false,
  },
  {
  id: "add8",
  username: "vienna_trail",
  avatar: "https://i.pravatar.cc/60?img=14",
  flag: "https://flagcdn.com/24x18/at.png",
  country: "Austria",
  timeAgo: "8 months ago",
  rating: 5,
  text: "Outdoor gear store with helpful product filters and seasonal inventory handling. Customers find the right kit faster than on our old site.",
  priceRange: "$720",
  duration: "15 days",
  serviceType: "Alpine Sports Store + Weather API",
  gigImage: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609382/IMG-20250921-WA0029_dcgxl0.jpg",
  showHelpful: true,
  },
  {
  id: "add7",
  username: "lisbon_pattern",
  avatar: "https://i.pravatar.cc/60?img=43",
  flag: "https://flagcdn.com/24x18/pt.png",
  country: "Portugal",
  timeAgo: "8 months ago",
  rating: 5,
  text: "Tile brand store with pattern previews that help customers decide faster. Custom design requests are easier to manage now.",
  priceRange: "$480",
  duration: "11 days",
  serviceType: "Tile Design Studio",
  gigImage: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609389/IMG-20250921-WA0033_crg1lz.jpg",
  reply: "Glad the visualization tools are helping buyers see the patterns clearly.",
  showHelpful: false,
  },
  {
  id: "fr2",
  username: "berlin_basics",
  avatar: "https://i.pravatar.cc/60?img=20",
  flag: "https://flagcdn.com/24x18/de.png",
  timeAgo: "3 weeks ago",
  rating: 5,
  text: "Communication was sharp and the store converts better after his optimization pass. Analytics, page speed, and product page SEO all got a proper cleanup. Professional end to end.",
  priceRange: "$320",
  duration: "6 days",
  serviceType: "Store Optimization",
  gigImage: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609405/IMG-20250921-WA0043_pdhfii.jpg",
  showHelpful: true,
  },
  {
  id: "fr8",
  username: "cape_jewels",
  avatar: "https://i.pravatar.cc/60?img=12",
  flag: "https://flagcdn.com/24x18/za.png",
  timeAgo: "3 months ago",
  rating: 5,
  text: "Jewelry store looks premium — zoom, payments, and trust signals are dialed in. Meta Ads traffic has been consistently higher quality since launch.",
  priceRange: "$420",
  duration: "9 days",
  serviceType: "Jewelry Store + Ads",
  gigImage: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609382/IMG-20250921-WA0029_dcgxl0.jpg",
  showHelpful: true,
  },
  {
  id: "add3",
  username: "athens_craft",
  avatar: "https://i.pravatar.cc/60?img=41",
  flag: "https://flagcdn.com/24x18/gr.png",
  country: "Greece",
  timeAgo: "6 months ago",
  rating: 5,
  text: "Story-driven store for our pottery line. Custom options and shipping abroad work well — we've opened markets we couldn't reach before.",
  priceRange: "$360",
  duration: "9 days",
  serviceType: "Cultural Artisan Store",
  gigImage: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609382/IMG-20250921-WA0029_dcgxl0.jpg",
  reply: "Honored to help your craft reach new customers. Thank you!",
  showHelpful: false,
  },
  {
  id: "add6",
  username: "budapest_cellar",
  avatar: "https://i.pravatar.cc/60?img=36",
  flag: "https://flagcdn.com/24x18/hu.png",
  country: "Hungary",
  timeAgo: "7 months ago",
  rating: 5,
  text: "Wine store features (age checks, tasting notes, pairings) all work as promised. Customers spend more time browsing — in a good way.",
  priceRange: "$650",
  duration: "13 days",
  serviceType: "Wine E-commerce + Features",
  gigImage: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609402/IMG-20250921-WA0039_htnlsc.jpg",
  showHelpful: true,
  },
  {
  id: "add4",
  username: "warsaw_glow",
  avatar: "https://i.pravatar.cc/60?img=19",
  flag: "https://flagcdn.com/24x18/pl.png",
  country: "Poland",
  timeAgo: "6 months ago",
  rating: 5,
  text: "Elegant amber jewelry store with trust-building product details. Design feels premium without slowing the site down.",
  priceRange: "$440",
  duration: "10 days",
  serviceType: "Jewelry Authentication Store",
  gigImage: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609381/IMG-20250921-WA0028_bwhztb.jpg",
  showHelpful: true,
  },
  {
  id: "fr6",
  username: "stockholm_well",
  avatar: "https://i.pravatar.cc/60?img=40",
  flag: "https://flagcdn.com/24x18/se.png",
  timeAgo: "2 months ago",
  rating: 5,
  text: "He built our wellness store and connected it cleanly to our tools. Google Ads have stayed profitable, and follow-up support has been better than expected.",
  priceRange: "$290",
  duration: "6 days",
  serviceType: "Wellness Store + Ads",
  gigImage: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609506/IMG-20250921-WA0092_ieopxm.jpg",
  showHelpful: true,
  },
  {
  id: "fr4",
  username: "sydney_stacks",
  avatar: "https://i.pravatar.cc/60?img=25",
  flag: "https://flagcdn.com/24x18/au.png",
  timeAgo: "1 month ago",
  rating: 5,
  text: "My dropshipping store finally looks legit. Product research, supplier flow, and theme setup were handled carefully. We saw the first orders inside the first week.",
  priceRange: "$450",
  duration: "7 days",
  serviceType: "Dropshipping Store",
  gigImage: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609504/IMG-20250921-WA0090_g6lmty.jpg",
  showHelpful: true,
  },
  {
  id: "fr3",
  username: "maple_markets",
  avatar: "https://i.pravatar.cc/60?img=47",
  flag: "https://flagcdn.com/24x18/ca.png",
  timeAgo: "1 month ago",
  rating: 5,
  text: "On time, documented, and easy to follow. The Facebook Ads setup started producing leads the same week. Great value for a clean handoff.",
  priceRange: "$150",
  duration: "3 days",
  serviceType: "Facebook Ads Setup",
  gigImage: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609506/IMG-20250921-WA0092_ieopxm.jpg",
  reply: "Glad the ads are live and working — here if you need scaling support.",
  showHelpful: false,
  },
  {
  id: "fr10",
  username: "brussels_bites",
  avatar: "https://i.pravatar.cc/60?img=38",
  flag: "https://flagcdn.com/24x18/be.png",
  timeAgo: "4 months ago",
  rating: 5,
  text: "Premium food brand store looks exactly right. Subscriptions and shipping options work, and conversion has beaten what we had on the old site.",
  priceRange: "$480",
  duration: "10 days",
  serviceType: "Premium Food Store",
  gigImage: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609395/IMG-20250921-WA0036_pd32aq.jpg",
  showHelpful: true,
  },
  {
  id: "add1",
  username: "copenhagen_form",
  avatar: "https://i.pravatar.cc/60?img=16",
  flag: "https://flagcdn.com/24x18/dk.png",
  country: "Denmark",
  timeAgo: "5 months ago",
  rating: 5,
  text: "Minimal furniture store that matches our brand. Variants and inventory behave correctly, and browsing feels simple on mobile.",
  priceRange: "$520",
  duration: "11 days",
  serviceType: "Furniture Store Build",
  gigImage: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609402/IMG-20250921-WA0039_htnlsc.jpg",
  reply: "Loved the aesthetic — happy we got the UX to match your pieces.",
  showHelpful: false,
  },
  {
  id: "add2",
  username: "dublin_harvest",
  avatar: "https://i.pravatar.cc/60?img=24",
  flag: "https://flagcdn.com/24x18/ie.png",
  country: "Ireland",
  timeAgo: "5 months ago",
  rating: 5,
  text: "Organic marketplace build with subscriptions that customers actually use. SEO improvements showed up in search visibility within weeks.",
  priceRange: "$680",
  duration: "14 days",
  serviceType: "Multi-vendor Marketplace",
  gigImage: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609389/IMG-20250921-WA0033_crg1lz.jpg",
  showHelpful: true,
  },
  {
  id: "fr7",
  username: "madrid_clay",
  avatar: "https://i.pravatar.cc/60?img=8",
  flag: "https://flagcdn.com/24x18/es.png",
  timeAgo: "3 months ago",
  rating: 5,
  text: "Beautiful store for my handmade ceramics. Inventory, galleries, and international shipping options all work without headaches. Customers keep commenting on how easy checkout feels.",
  priceRange: "$340",
  duration: "8 days",
  serviceType: "Artisan Store Build",
  gigImage: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609389/IMG-20250921-WA0033_crg1lz.jpg",
  reply: "Your work deserves a storefront this clean — thank you for trusting Bofowo Agency.",
  showHelpful: false,
  },
  {
  id: "add5",
  username: "prague_glass",
  avatar: "https://i.pravatar.cc/60?img=27",
  flag: "https://flagcdn.com/24x18/cz.png",
  country: "Czech Republic",
  timeAgo: "7 months ago",
  rating: 5,
  text: "Gallery-style crystal store with strong product presentation. The wholesale section made dealer orders much easier for our team.",
  priceRange: "$590",
  duration: "12 days",
  serviceType: "Crystal Gallery + B2B Portal",
  gigImage: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609395/IMG-20250921-WA0036_pd32aq.jpg",
  reply: "Thank you — the product photography deserved a gallery that does it justice.",
  showHelpful: false,
  },
  {
  id: "add10",
  username: "tallinn_bytes",
  avatar: "https://i.pravatar.cc/60?img=21",
  flag: "https://flagcdn.com/24x18/ee.png",
  country: "Estonia",
  timeAgo: "9 months ago",
  rating: 5,
  text: "Digital services marketplace build with secure checkout and reputation scoring. Complex project, delivered without drama.",
  priceRange: "$850",
  duration: "18 days",
  serviceType: "Digital Services Marketplace",
  gigImage: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609395/IMG-20250921-WA0036_pd32aq.jpg",
  reply: "Thanks for the ambitious brief — great building this with your team.",
  showHelpful: false,
  },
  {
  id: "fr1",
  username: "london_listings",
  avatar: "https://i.pravatar.cc/60?img=15",
  flag: "https://flagcdn.com/24x18/gb.png",
  timeAgo: "2 weeks ago",
  rating: 5,
  text: "Clear process and solid delivery. Bofowo Agency built my Shopify store from zero — clean design, smooth checkout, and it already feels ready for ads. I'll hire again for listings and marketing.",
  priceRange: "$180",
  duration: "4 days",
  serviceType: "Shopify Store Setup",
  gigImage: "https://res.cloudinary.com/dr83qj6bf/image/upload/v1758609505/IMG-20250921-WA0091_ymtuvy.jpg",
  reply: "Thank you! Excited to help with the next phase of your store growth.",
  showHelpful: false,
  },
];
